apiVersion: v1
kind: Service
metadata:
  name: api-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: api
  ports:
    - name: api
      port: 5000
      targetPort: 5000
    - name: stream
      port: 8000
      targetPort: 8000
